version: '2'
services:
  mysql:
    container_name: keycloak_mysql
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
    image: jboss/keycloak:12.0.4
    restart: unless-stopped
    container_name: keycloak
    
    environment:
      HOST_MAP_IP: ${HOST_MAP_IP}
      HOST_NAME: ${HOST_NAME}
      KEYCLOAK_HOSTNAME: ${HOST_NAME}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      JDBC_PARAMS: ${JDBC_PARAMS}   
      DEV_KEYCLOAK_THEMES_FOLDER: ${DEV_KEYCLOAK_THEMES_FOLDER}
      DEV_KEYCLOAK_THEME: ${DEV_KEYCLOAK_THEME}
      KEYCLOAK_WELCOME_THEME: ${DEV_KEYCLOAK_THEME}
      KEYCLOAK_DEFAULT_THEME: ${DEV_KEYCLOAK_THEME}
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak_mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    ports:
      - ${HOST_MAP_IP}:80:8080  # http#      - ${HOST_MAP_IP}89:8009 # Undertow AJP listener ajp listening on 0.0.0.0:8009
      - ${HOST_MAP_IP}:443:8443 # https
    volumes:
      - ./standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      - ${DEV_KEYCLOAK_THEMES_FOLDER}/${DEV_KEYCLOAK_THEME}:/opt/jboss/keycloak/themes/${DEV_KEYCLOAK_THEME}:ro
      - ${DEV_KEYCLOAK_THEMES_FOLDER}/${DEV_KEYCLOAK_THEME}/common/resources/img/favicon.ico:/opt/jboss/keycloak/themes/common/resources/img/favicon.ico:ro

      - ./disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli
#      - ./certs:/etc/x509/https:ro
#      - ./themes/Layer8:/opt/jboss/keycloak/themes/Layer8:ro
#      - ./themes/base:/opt/jboss/keycloak/themes/base:ro
#      - ./config/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml:ro
    depends_on:
      - mysql
