version: '2'

volumes:
  data:

services:
    PORTAINER:
        image: portainer/portainer:latest
        restart: unless-stopped
        container_name: portainers
        volumes:
          - data:/data
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - ${HOST_MAP_IP}:${HOST_MAP_PORT}:9000     # portainer api http
        command: --no-auth




